#ifndef POWERFAILUREALARMCOMON_H_
#define POWERFAILUREALARMCOMON_H_

#define SETTINGS_DEFAULT_DELAY 5*60
#define CONTACT_MAX_COUNT 3


#define CONTACT_MAX_NAME_SIZE 12
#define CONTACT_MAX_NUMBER_SIZE 12

#endif /* POWERFAILUREALARMCOMON_H_ */
